function [png] = leather_soccer_boot_pdf()

png.PN_name = 'Leather Soccer Boot Manufacturing';

% Set of all the Places
png.set_of_Ps = {
    'pManufacturingStage',...
    'pMaterialCutting',...
    'pSeaming',...
    'pSoleAttachment',...
    'pEyeletFixing',...
    'pLaceInsertion',...
    'pDesignImprinting',...
    'pSizeNumbering',...
    'pSortingMatching',... 
    'pQualityVerification',...
    'pQualityConfirmed',...
    'pDisposePoorQuality',...
    'pCleaning',...
    'pPackagingStage',...
    'pReadyForShipment',...
};

% Set of all the Transitions
png.set_of_Ts = {
    'tMoveMaterialToCuttingStage',...
    'tMaterialCutting',...
    'tSeaming',...
    'tSoleAttachment',...
    'tEyeletFixing',...
    'tLaceInsertion',... 
    'tDesignImprinting',...
    'tSizeNumbering',...
    'tSortingMatching',... 
    'tQualityVerification',...
    'tDisposePoorQuality',...
    'tTransferConfirmedQuality',...
    'tCleaning',...
    'tPackagingStage',... 
   
};

% Set of all the Arcs
png.set_of_As = {
    'pManufacturingStage', 'tMoveMaterialToCuttingStage', 1,...
    'tMoveMaterialToCuttingStage', 'pMaterialCutting', 1,...
    'pMaterialCutting', 'tMaterialCutting', 1,...
    'tMaterialCutting', 'pSeaming', 120,...
    'pSeaming', 'tSeaming', 120,...
    'tSeaming', 'pSoleAttachment', 120,... 
    'pSoleAttachment', 'tSoleAttachment', 120,...  
    'tSoleAttachment', 'pEyeletFixing', 120,...
    'pEyeletFixing', 'tEyeletFixing', 120,...
    'tEyeletFixing', 'pLaceInsertion', 120,...
    'pLaceInsertion', 'tLaceInsertion', 120,... 
    'tLaceInsertion', 'pDesignImprinting', 120,...
    'pDesignImprinting', 'tDesignImprinting', 120,...
    'tDesignImprinting', 'pSizeNumbering', 120,...
    'pSizeNumbering', 'tSizeNumbering', 120,...
    'tSizeNumbering', 'pSortingMatching', 120,...
    'pSortingMatching', 'tSortingMatching', 120,...
    'tSortingMatching', 'pQualityVerification', 120,...
    'pQualityVerification', 'tQualityVerification', 1,...
    'tQualityVerification', 'pQualityConfirmed', 1,...
    'pQualityConfirmed', 'tDisposePoorQuality', 1,...
    'tDisposePoorQuality', 'pDisposePoorQuality',1,...
    'pQualityConfirmed', 'tTransferConfirmedQuality', 1,...
    'tTransferConfirmedQuality', 'pCleaning', 120,...
    'pCleaning', 'tCleaning', 120,...
    'tCleaning', 'pPackagingStage', 120,...
    'pPackagingStage', 'tPackagingStage', 120,...
    'tPackagingStage', 'pReadyForShipment', 120
};

end
